import { fallbackMarket, fallbackDefi, fallbackNews } from './_data.js';
export function json(data, status=200){ return new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'}}); }
export async function getJson(url, options={}){ const r=await fetch(url,{...options,headers:{accept:'application/json',...(options.headers||{})}}); const txt=await r.text(); let data; try{data=JSON.parse(txt)}catch{data={raw:txt}}; if(!r.ok) throw new Error(`upstream_${r.status}`); return data; }
export function normMarket(rows=[]){ return rows.map(x=>({symbol:String(x.symbol||x.tokenSymbol||'ASSET').toUpperCase(),name:x.name||x.tokenName||x.symbol||'Asset',price:Number(x.current_price??x.price??x.lastPrice??0),change:Number(x.price_change_percentage_24h??x.change24h??x.priceChangePercent??0),volume:Number(x.total_volume??x.volume??x.quoteVolume??0),marketCap:Number(x.market_cap??x.marketCap??0),score:Math.round(70+Math.max(-10,Math.min(20,Number(x.price_change_percentage_24h??x.priceChangePercent??0)*2)))})); }
export async function marketData(){
  const apiKey=process.env.SOSOVALUE_API_KEY; const base=(process.env.SOSOVALUE_BASE_URL||'https://openapi.sosovalue.com/openapi/v1').replace(/\/+$/,''); const path=process.env.SOSOVALUE_MARKET_PATH||'/token/market/list';
  if(apiKey){ try{ const data=await getJson(`${base}${path}`,{headers:{'x-soso-api-key':apiKey,'X-SOSO-API-KEY':apiKey}}); const arr=data?.data?.list||data?.data?.data||data?.data||data?.list||[]; if(Array.isArray(arr)&&arr.length) return {source:'primary',data:normMarket(arr)}; }catch{} }
  try{ const cg=await getJson('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin,ethereum,solana,binancecoin,ripple,chainlink,arbitrum,uniswap&order=market_cap_desc&per_page=20&page=1&sparkline=false&price_change_percentage=24h'); return {source:'market',data:normMarket(cg)}; }catch{}
  try{ const symbols=encodeURIComponent(JSON.stringify(['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','LINKUSDT'])); const b=await getJson(`https://api.binance.com/api/v3/ticker/24hr?symbols=${symbols}`); return {source:'exchange',data:normMarket(b.map(x=>({symbol:x.symbol.replace('USDT',''),name:x.symbol.replace('USDT',''),lastPrice:x.lastPrice,priceChangePercent:x.priceChangePercent,quoteVolume:x.quoteVolume})))}; }catch{}
  return {source:'resilience',data:fallbackMarket};
}
export async function newsData(){ const key=process.env.SOSOVALUE_API_KEY; const base=(process.env.SOSOVALUE_BASE_URL||'https://openapi.sosovalue.com/openapi/v1').replace(/\/+$/,''); const path=process.env.SOSOVALUE_NEWS_PATH||'/news/list'; if(key){try{const d=await getJson(`${base}${path}`,{headers:{'x-soso-api-key':key,'X-SOSO-API-KEY':key}}); const arr=d?.data?.list||d?.data||d?.list||[]; if(Array.isArray(arr)&&arr.length)return{source:'primary',data:arr.slice(0,8).map(n=>({title:n.title||n.name||'Market update',source:n.source||n.author||'Market News',sentiment:n.sentiment||'Neutral'}))};}catch{}}
try{const d=await getJson('https://min-api.cryptocompare.com/data/v2/news/?lang=EN');return{source:'news',data:(d.Data||[]).slice(0,8).map(n=>({title:n.title,source:n.source_info?.name||n.source,sentiment:'Live'}))}}catch{} return{source:'resilience',data:fallbackNews}; }
export async function defiData(){ try{const d=await getJson('https://api.llama.fi/protocols');return{source:'defillama',data:(d||[]).sort((a,b)=>(b.tvl||0)-(a.tvl||0)).slice(0,8).map(p=>({name:p.name,category:p.category||'DeFi',tvl:p.tvl||0,change_1d:p.change_1d||0}))}}catch{} return{source:'resilience',data:fallbackDefi}; }
